[env]
# Terminal emulator
TERM = "xterm-256color"

# Font
[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Medium"

[general]
# Automaticcally reload the configuration when changed
live_config_reload = true

# Color scheme
import = ["~/.config/alacritty/cattpucin/catppuccin-mocha.toml"]
